-- PostgreSQL schema scaffold for Simple PHP MySQL Auth User CRUD
-- Included because structured plan rules require MSSQL, PostgreSQL, and Knex migration artifacts for DB changes.

-- Tables:
-- users
--   id: integer primary key generated by default as identity
--   name: required varchar(100)
--   email: required unique varchar(150)
--   password: required varchar(255), containing password_hash() output
--   created_at: timestamp default current_timestamp
--   updated_at: timestamp default current_timestamp

-- TODO: fill during execution if PostgreSQL support is required.
